with open('C:\\Users\\Noah\\Desktop\\mfy-app\\src\\pages\\Board.tsx', 'r') as f:
    lines = f.readlines()

# Find the insertion point - after "{anime.length > 0 && <AnimeSection items={anime} />}"
insert_idx = None
for i, line in enumerate(lines):
    if '{anime.length > 0 && <AnimeSection items={anime} />}' in line:
        insert_idx = i + 1  # Insert after this line
        break

print(f"Insert at line: {insert_idx+1}")

if insert_idx is not None:
    new_sections = [
        '\n',
        '        {/* Providers Section */}\n',
        '        {providers.length > 0 && (\n',
        '          <section style={{ marginTop: 16 }}>\n',
        '            <div style={{ \n',
        '              display: \'flex\', \n',
        '              justifyContent: \'space-between\', \n',
        '              alignItems: \'center\', \n',
        '              marginBottom: 16 \n',
        '            }}>\n',
        '              <h2 style={{ fontSize: \'1.25rem\', fontWeight: \'bold\', color: \'white\', margin: 0 }}>\n',
        '                Streaming Providers\n',
        '              </h2>\n',
        '              <button \n',
        '                style={{ \n',
        '                  color: \'rgba(255,255,255,0.5)\', \n',
        '                  background: \'none\', \n',
        '                  border: \'none\', \n',
        '                  fontSize: \'0.875rem\', \n',
        '                  cursor: \'pointer\',\n',
        '                  padding: 0,\n',
        '                  display: \'flex\',\n',
        '                  alignItems: \'center\',\n',
        '                  gap: 4\n',
        '                }}\n',
        '                onClick={() => setCurrentPage(\'providers\')}\n',
        '              >\n',
        '                View All\n',
        '                <ArrowRight size={14} style={{ display: \'inline\', verticalAlign: \'middle\' }} />\n',
        '              </button>\n',
        '            </div>\n',
        '            <div\n',
        '              ref={providerRef}\n',
        '              style={{\n',
        '                display: \'flex\',\n',
        '                gap: 16,\n',
        '                overflowX: \'auto\',\n',
        '                scrollBehavior: \'smooth\',\n',
        '                WebkitOverflowScrolling: \'touch\',\n',
        '                paddingBottom: 16\n',
        '              }}\n',
        '            >\n',
        '              {providers.slice(0, 8).map((provider) => (\n',
        '                <div key={provider.id} style={{ flexShrink: 0, width: 320, minWidth: 280 }}>\n',
        '                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] mb-4" style={{ cursor: \'pointer\' }}>\n',
        '                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#FF1493]/20 to-[#00E5FF]/20 border border-[#FF1493]/30 flex items-center justify-center flex-shrink-0">\n',
        '                      <Film className="w-6 h-6 text-[#FF1493]" />\n',
        '                    </div>\n',
        '                    <div>\n',
        '                      <p className="text-sm font-semibold text-white">{provider.name}</p>\n',
        '                      <p className="text-[11px] text-white/35">{(provider.movies?.length || 0) + (provider.tv?.length || 0)} titles</p>\n',
        '                    </div>\n',
        '                  </div>\n',
        '                  <div style={{ display: \'flex\', gap: 8, overflowX: \'auto\', scrollBehavior: \'smooth\', paddingBottom: 8 }}>\n',
        '                    {(provider.movies?.slice(0, 4) || []).map((item: any) => (\n',
        '                      <button key={item.id} onClick={() => goDetail(item.id, \'movie\')} style={{ flexShrink: 0, width: 120, flexShrink: 0 }} className="text-left">\n',
        '                        <img src={`${POSTER_URL}${item.poster_path}`} alt="" className="w-full aspect-[2/3] rounded-lg object-cover mb-2" loading="lazy" />\n',
        '                        <p className="text-[11px] font-medium text-white truncate">{item.title}</p>\n',
        '                        <p className="text-[10px] text-white/30">{item.release_date?.slice(0,4) || \'\'}</p>\n',
        '                      </button>\n',
        '                    ))}\n',
        '                    {(provider.tv?.slice(0, 4) || []).map((item: any) => (\n',
        '                      <button key={item.id} onClick={() => goDetail(item.id, \'tv\')} style={{ flexShrink: 0, width: 120, flexShrink: 0 }} className="text-left">\n',
        '                        <img src={`${POSTER_URL}${item.poster_path}`} alt="" className="w-full aspect-[2/3] rounded-lg object-cover mb-2" loading="lazy" />\n',
        '                        <p className="text-[11px] font-medium text-white truncate">{item.name}</p>\n',
        '                        <p className="text-[10px] text-white/30">{item.first_air_date?.slice(0,4) || \'\'}</p>\n',
        '                      </button>\n',
        '                    ))}\n',
        '                  </div>\n',
        '                </div>\n',
        '              ))}\n',
        '            </div>\n',
        '          </section>\n',
        '        )}\n',
        '\n',
        '\n',
        '        {/* Franchises Section */}\n',
        '        {franchisesData.length > 0 && (\n',
        '          <section style={{ marginTop: 16 }}>\n',
        '            <div style={{ \n',
        '              display: \'flex\', \n',
        '              justifyContent: \'space-between\', \n',
        '              alignItems: \'center\', \n',
        '              marginBottom: 16 \n',
        '            }}>\n',
        '              <h2 style={{ fontSize: \'1.25rem\', fontWeight: \'bold\', color: \'white\', margin: 0 }}>\n',
        '                Franchises & Collections\n',
        '              </h2>\n',
        '              <button \n',
        '                style={{ \n',
        '                  color: \'rgba(255,255,255,0.5)\', \n',
        '                  background: \'none\', \n',
        '                  border: \'none\', \n',
        '                  fontSize: \'0.875rem\', \n',
        '                  cursor: \'pointer\',\n',
        '                  padding: 0,\n',
        '                  display: \'flex\',\n',
        '                  alignItems: \'center\',\n',
        '                  gap: 4\n',
        '                }}\n',
        '                onClick={() => setCurrentPage(\'franchises\')}\n',
        '              >\n',
        '                View All\n',
        '                <ArrowRight size={14} style={{ display: \'inline\', verticalAlign: \'middle\' }} />\n',
        '              </button>\n',
        '            </div>\n',
        '            <div\n',
        '              ref={franchiseRef}\n',
        '              style={{\n',
        '                display: \'flex\',\n',
        '                gap: 16,\n',
        '                overflowX: \'auto\',\n',
        '                scrollBehavior: \'smooth\',\n',
        '                WebkitOverflowScrolling: \'touch\',\n',
        '                paddingBottom: 16\n',
        '              }}\n',
        '            >\n',
        '              {franchisesData.slice(0, 8).map((franchise) => (\n',
        '                <div key={franchise.id} style={{ flexShrink: 0, width: 320, minWidth: 280 }}>\n',
        '                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] mb-4" style={{ cursor: \'pointer\' }}>\n',
        '                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#FF1493]/20 to-[#00E5FF]/20 border border-[#FF1493]/30 flex items-center justify-center flex-shrink-0">\n',
        '                      <BookOpen className="w-6 h-6 text-[#FF1493]" />\n',
        '                    </div>\n',
        '                    <div>\n',
        '                      <p className="text-sm font-semibold text-white">{franchise.name}</p>\n',
        '                      <p className="text-[11px] text-white/35">{franchise.parts?.length || 0} titles</p>\n',
        '                    </div>\n',
        '                  </div>\n',
        '                  <div style={{ display: \'flex\', gap: 8, overflowX: \'auto\', scrollBehavior: \'smooth\', paddingBottom: 8 }}>\n',
        '                    {(franchise.parts || []).slice(0, 4).map((item: any) => (\n',
        '                      <button key={item.id} onClick={() => goDetail(item.id, item.media_type === \'tv\' ? \'tv\' : \'movie\')} style={{ flexShrink: 0, width: 120, flexShrink: 0 }} className="text-left">\n',
        '                        <img src={`${POSTER_URL}${item.poster_path}`} alt="" className="w-full aspect-[2/3] rounded-lg object-cover mb-2" loading="lazy" />\n',
        '                        <p className="text-[11px] font-medium text-white truncate">{item.title || item.name}</p>\n',
        '                        <p className="text-[10px] text-white/30">{item.release_date?.slice(0,4) || item.first_air_date?.slice(0,4) || \'\'}</p>\n',
        '                      </button>\n',
        '                    ))}\n',
        '                  </div>\n',
        '                </div>\n',
        '              ))}\n',
        '            </div>\n',
        '          </section>\n',
        '        )}\n',
        '\n',
        '\n',
        '        {/* Manga Section */}\n',
        '        {manga.length > 0 && (\n',
        '          <section style={{ marginTop: 16 }}>\n',
        '            <div style={{ \n',
        '              display: \'flex\', \n',
        '              justifyContent: \'space-between\', \n',
        '              alignItems: \'center\', \n',
        '              marginBottom: 16 \n',
        '            }}>\n',
        '              <h2 style={{ fontSize: \'1.25rem\', fontWeight: \'bold\', color: \'white\', margin: 0 }}>\n',
        '                Manga\n',
        '              </h2>\n',
        '              <button \n',
        '                style={{ \n',
        '                  color: \'rgba(255,255,255,0.5)\', \n',
        '                  background: \'none\', \n',
        '                  border: \'none\', \n',
        '                  fontSize: \'0.875rem\', \n',
        '                  cursor: \'pointer\',\n',
        '                  padding: 0,\n',
        '                  display: \'flex\',\n',
        '                  alignItems: \'center\',\n',
        '                  gap: 4\n',
        '                }}\n',
        '                onClick={() => setCurrentPage(\'manga\')}\n',
        '              >\n',
        '                View All\n',
        '                <ArrowRight size={14} style={{ display: \'inline\', verticalAlign: \'middle\' }} />\n',
        '              </button>\n',
        '            </div>\n',
        '            <div\n',
        '              ref={mangaRef}\n',
        '              style={{\n',
        '                display: \'flex\',\n',
        '                gap: GAP,\n',
        '                overflowX: \'auto\',\n',
        '                scrollBehavior: \'smooth\',\n',
        '                WebkitOverflowScrolling: \'touch\',\n',
        '                paddingBottom: 16\n',
        '              }}\n',
        '            >\n',
        '              {manga.slice(0, 16).map((item) => (\n',
        '                <div\n',
        '                  key={item.id}\n',
        '                  className="poster-card"\n',
        '                  role="button"\n',
        '                  tabIndex={0}\n',
        '                  onClick={() => {\n',
        '                    // Open manga detail page\n',
        '                    setCurrentPage(\'manga-detail\')\n',
        '                  }}\n',
        '                  style={{ flexShrink: 0, width: POSTER_W }}\n',
        '                >\n',
        '                  {item.coverImage ? (\n',
        '                    <img \n',
        '                      src={item.coverImage} \n',
        '                      alt={item.title?.english || item.title?.romaji || item.title} \n',
        '                      loading="lazy" \n',
        '                      style={{ width: \'100%\', height: POSTER_H, objectFit: \'cover\' }}\n',
        '                      onError={(e) => { const el = e.currentTarget; el.onerror = null; el.style.display = \'none\'; el.parentElement?.classList.add(\'has-fallback\') }}\n',
        '                    />\n',
        '                  ) : (\n',
        '                    <div className="poster-fallback">{item.title?.english || item.title?.romaji || item.title}</div>\n',
        '                  )}\n',
        '                  <div className="poster-play"><Play size={18} fill="#fff" /></div>\n',
        '                  <div className="poster-overlay">\n',
        '                    <div className="poster-meta-title">{item.title?.english || item.title?.romaji || item.title}</div>\n',
        '                    <div className="poster-meta-sub">\n',
        '                      <Stars value={item.averageScore ? item.averageScore / 10 : 0} size={12} />\n',
        '                      <span className="ml-1 text-[10px] text-white/60">{item.status}</span>\n',
        '                    </div>\n',
        '                  </div>\n',
        '                </div>\n',
        '              ))}\n',
        '            </div>\n',
        '          </section>\n',
        '        )}\n',
        '\n',
        '\n',
        '        {/* Airing Schedule Section */}\n',
        '        {(airingAnime.length > 0 || airingTVShows.length > 0) && (\n',
        '          <section style={{ marginTop: 16 }}>\n',
        '            <div style={{ \n',
        '              display: \'flex\', \n',
        '              justifyContent: \'space-between\', \n',
        '              alignItems: \'center\', \n',
        '              marginBottom: 16 \n',
        '            }}>\n',
        '              <h2 style={{ fontSize: \'1.25rem\', fontWeight: \'bold\', color: \'white\', margin: 0 }}>\n',
        '                Airing Schedule\n',
        '              </h2>\n',
        '              <button \n',
        '                style={{ \n',
        '                  color: \'rgba(255,255,255,0.5)\', \n',
        '                  background: \'none\', \n',
        '                  border: \'none\', \n',
        '                  fontSize: \'0.875rem\', \n',
        '                  cursor: \'pointer\',\n',
        '                  padding: 0,\n',
        '                  display: \'flex\',\n',
        '                  alignItems: \'center\',\n',
        '                  gap: 4\n',
        '                }}\n',
        '                onClick={() => setCurrentPage(\'airing\')}\n',
        '              >\n',
        '                View All\n',
        '                <ArrowRight size={14} style={{ display: \'inline\', verticalAlign: \'middle\' }} />\n',
        '              </button>\n',
        '            </div>\n',
        '            <div style={{ display: \'flex\', gap: 16, overflowX: \'auto\', scrollBehavior: \'smooth\', paddingBottom: 16 }}>\n',
        '              {/* Airing Anime */}\n',
        '              {airingAnime.length > 0 && (\n',
        '                <div style={{ flexShrink: 0, width: 320, minWidth: 280 }}>\n',
        '                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] mb-4" style={{ cursor: \'pointer\' }}>\n',
        '                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#FF1493]/20 to-[#00E5FF]/20 border border-[#FF1493]/30 flex items-center justify-center flex-shrink-0">\n',
        '                      <Sparkles className="w-6 h-6 text-[#FF1493]" />\n',
        '                    </div>\n',
        '                    <div>\n',
        '                      <p className="text-sm font-semibold text-white">Airing Anime</p>\n',
        '                      <p className="text-[11px] text-white/35">{airingAnime.length} airing now</p>\n',
        '                    </div>\n',
        '                  </div>\n',
        '                  <div style={{ display: \'flex\', gap: 8, overflowX: \'auto\', scrollBehavior: \'smooth\', paddingBottom: 8 }}>\n',
        '                    {airingAnime.slice(0, 8).map((anime) => (\n',
        '                      <div key={anime.id} style={{ flexShrink: 0, width: 140 }} className="text-left">\n',
        '                        <div style={{ position: \'relative\', width: \'100%\', paddingTop: \'150%\' }}>\n',
        '                          {anime.coverImage ? (\n',
        '                            <img src={anime.coverImage} alt="" style={{ position: \'absolute\', inset: 0, width: \'100%\', height: \'100%\', objectFit: \'cover\', borderRadius: 8 }} loading="lazy" />\n',
        '                          ) : (\n',
        '                            <div style={{ position: \'absolute\', inset: 0, borderRadius: 8, background: \'rgba(255,255,255,0.05)\', display: \'flex\', alignItems: \'center\', justifyContent: \'center\' }}>\n',
        '                              <Sparkles size={24} color="rgba(255,255,255,0.3)" />\n',
        '                            </div>\n',
        '                          )}\n',
        '                        </div>\n',
        '                        <div className="mt-2">\n',
        '                          <p className="text-white text-xs truncate">{anime.titleEnglish || anime.titleRomaji || anime.title}</p>\n',
        '                          <p className="text-white/40 text-[10px]">\n',
        '                            Ep {anime.nextAiringEpisode || \'?\'} \u00b7 {anime.timeUntilAiring ? `${Math.round(anime.timeUntilAiring / 60)}m` : \'Soon\'}\n',
        '                          </p>\n',
        '                        </div>\n',
        '                      </div>\n',
        '                    ))}\n',
        '                  </div>\n',
        '                </div>\n',
        '              )}\n',
        '              \n',
        '              {/* Airing TV Shows */}\n',
        '              {airingTVShows.length > 0 && (\n',
        '                <div style={{ flexShrink: 0, width: 320, minWidth: 280 }}>\n',
        '                  <div className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] mb-4" style={{ cursor: \'pointer\' }}>\n',
        '                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#FF1493]/20 to-[#00E5FF]/20 border border-[#FF1493]/30 flex items-center justify-center flex-shrink-0">\n',
        '                      <Tv className="w-6 h-6 text-[#FF1493]" />\n',
        '                    </div>\n',
        '                    <div>\n',
        '                      <p className="text-sm font-semibold text-white">Airing TV Shows</p>\n',
        '                      <p className="text-[11px] text-white/35">{airingTVShows.length} airing now</p>\n',
        '                    </div>\n',
        '                  </div>\n',
        '                  <div style={{ display: \'flex\', gap: 8, overflowX: \'auto\', scrollBehavior: \'smooth\', paddingBottom: 8 }}>\n',
        '                    {airingTVShows.slice(0, 4).map((show) => (\n',
        '                      <div key={show.id} style={{ flexShrink: 0, width: 140 }} className="text-left">\n',
        '                        <div style={{ position: \'relative\', width: \'100%\', paddingTop: \'150%\' }}>\n',
        '                          {show.posterPath ? (\n',
        '                            <img src={`${POSTER_URL}${show.posterPath}`} alt="" style={{ position: \'absolute\', inset: 0, width: \'100%\', height: \'100%\', objectFit: \'cover\', borderRadius: 8 }} loading="lazy" />\n',
        '                          ) : (\n',
        '                            <div style={{ position: \'absolute\', inset: 0, borderRadius: 8, background: \'rgba(255,255,255,0.05)\', display: \'flex\', alignItems: \'center\', justifyContent: \'center\' }}>\n',
        '                              <Tv size={24} color="rgba(255,255,255,0.3)" />\n',
        '                            </div>\n',
        '                          )}\n',
        '                        </div>\n',
        '                        <div className="mt-2">\n',
        '                          <p className="text-white text-xs truncate">{show.name}</p>\n',
        '                          <p className="text-white/40 text-[10px]">\n',
        '                            Ep {show.nextEpisodeToAir?.episodeNumber || \'?\'} \u00b7 {show.nextEpisodeToAir?.airDate ? new Date(show.nextEpisodeToAir.airDate).toLocaleDateString() : \'Soon\'}\n',
        '                          </p>\n',
        '                        </div>\n',
        '                      </div>\n',
        '                    ))}\n',
        '                  </div>\n',
        '                </div>\n',
        '              )}\n',
        '            </div>\n',
        '          </section>\n',
        '        )}\n',
        '\n',
    ]
    
    # Insert the new sections
    for i, section_line in enumerate(new_sections):
        lines.insert(insert_idx + i, section_line)
    
    with open('C:\\Users\\Noah\\Desktop\\mfy-app\\src\\pages\\Board.tsx', 'w') as f:
        f.writelines(lines)
    print("Done inserting!")
else:
    print("Could not find insertion point")