import { Theme } from './engine'

// Built-in themes with logos and assets
export const builtInThemes: Theme[] = [
  {
    id: 'mfy-modern',
    name: 'MFY Modern',
    displayName: 'MFY Modern',
    description: 'Modern dark theme with pink-cyan accents',
    author: 'MFY Team',
    version: '1.0.0',
    previewImages: ['/logos/mfy-modern-1.png', '/logos/mfy-modern-2.png'],
    isBuiltIn: true,
    isActive: false,
    config: {
      colors: {
        primary: '#ff6b35',
        secondary: '#00e5ff',
        background: '#0a0a0f',
        surface: '#16161f',
        text: '#ffffff',
        muted: '#7d8593',
      },
      fonts: {
        display: "'Geist', sans-serif",
        heading: "'Geist', sans-serif",
        body: "'Inter', sans-serif",
        mono: "'Fira Code', monospace",
        ui: "'SF Mono', monospace",
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
    assets: {
      logo: '/logos/mfy-modern.svg',
      favicon: '/logos/favicon.ico',
    },
    layouts: {
      primary: 'sidebar',
      secondary: 'top-bar',
    },
    animations: {
      enabled: true,
      reducedMotion: false,
    },
    sounds: {
      enabled: false,
      volume: 0.5,
    },
  },

  {
    id: 'retroarch',
    name: 'RetroArch',
    displayName: 'RetroArch',
    description: 'RetroArch-inspired XMB interface',
    author: 'MFY Team',
    version: '1.0.0',
    previewImages: ['/logos/retroarch-1.png'],
    isBuiltIn: true,
    isActive: false,
    config: {
      colors: {
        primary: '#a50026',
        secondary: '#ffb74d',
        background: '#000000',
        surface: '#1a1a1a',
        text: '#e0e0e0',
        muted: '#666666',
      },
      fonts: {
        display: "'Orbitron', monospace",
        heading: "'Orbitron', monospace",
        body: "'Inter', sans-serif",
        mono: "'Fira Code', monospace",
        ui: "'Consolas', monospace",
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
    assets: {
      logo: '/logos/retroarch.svg',
      favicon: '/logos/favicon.ico',
    },
    layouts: {
      primary: 'grid',
      secondary: 'list',
    },
    animations: {
      enabled: true,
      reducedMotion: false,
    },
    sounds: {
      enabled: true,
      volume: 0.7,
    },
  },

  {
    id: 'xmb',
    name: 'XMB',
    displayName: 'XMB (PlayStation)',
    displayName: 'XMB',
    description: 'PlayStation XMB interface style',
    author: 'MFY Team',
    version: '1.0.0',
    previewImages: ['/logos/xmb-1.png'],
    isBuiltIn: true,
    isActive: false,
    config: {
      colors: {
        primary: '#0033a0',
        secondary: '#ffd700',
        background: '#000000',
        surface: '#0f0f0f',
        text: '#ffffff',
        muted: '#999999',
      },
      fonts: {
        display: "'Baskerville', serif",
        heading: "'Baskerville', serif",
        body: "'Inter', sans-serif",
        mono: "'Fira Code', monospace",
        ui: "'Consolas', monospace",
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
    assets: {
      logo: '/logos/xmb.svg',
      favicon: '/logos/favicon.ico',
    },
    layouts: {
      primary: 'vertical',
      secondary: 'horizontal',
    },
    animations: {
      enabled: false,
      reducedMotion: true,
    },
    sounds: {
      enabled: true,
      volume: 0.5,
    },
  },

  {
    id: 'ps2',
    name: 'PS2',
    displayName: 'PS2',
    description: 'PlayStation 2 dashboard style',
    author: 'MFY Team',
    version: '1.0.0',
    previewImages: ['/logos/ps2-1.png'],
    isBuiltIn: true,
    isActive: false,
    config: {
      colors: {
        primary: '#ff5c00',
        secondary: '#00aaff',
        background: '#0d0d0d',
        surface: '#1a1a1a',
        text: '#e0e0e0',
        muted: '#666666',
      },
      fonts: {
        display: "'Bebas Neue', sans-serif",
        heading: "'Bebas Neue', sans-serif",
        body: "'Inter', sans-serif",
        mono: "'Fira Code', monospace",
        ui: "'Consolas', monospace",
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
    assets: {
      logo: '/logos/ps2.svg',
      favicon: '/logos/favicon.ico',
    },
    layouts: {
      primary: 'grid',
      secondary: 'list',
    },
    animations: {
      enabled: true,
      reducedMotion: false,
    },
    sounds: {
      enabled: true,
      volume: 0.6,
    },
  },

  {
    id: 'psp',
    name: 'PSP',
    displayName: 'PSP',
    description: 'PlayStation Portable theme',
    author: 'MFY Team',
    version: '1.0.0',
    previewImages: ['/logos/psp-1.png'],
    isBuiltIn: true,
    isActive: false,
    config: {
      colors: {
        primary: '#0066cc',
        secondary: '#00ccff',
        background: '#0a0a0f',
        surface: '#14141a',
        text: '#ffffff',
        muted: '#777777',
      },
      fonts: {
        display: "'verdana', sans-serif",
        heading: "'verdana', sans-serif",
        body: "'Inter', sans-serif",
        mono: "'Fira Code', monospace",
        ui: "'Consolas', monospace",
      },
      fontSizes: {
        xs: '0.75rem',
        sm: '0.875rem',
        md: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      spacing: {
        xs: '0.25rem',
        sm: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
      },
      borderRadius: {
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
      },
    },
    assets: {
      logo: '/logos/psp.svg',
      favicon: '/logos/favicon.ico',
    },
    layouts: {
      primary: 'grid',
      secondary: 'list',
    },
    animations: {
      enabled: true,
      reducedMotion: false,
    },
    sounds: {
      enabled: true,
      volume: 0.5,
    },
  },
]